apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: rt-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: 'true'
spec:
  rules:
    - host: isambard-support.gw4.ac.uk
      http:
        paths:
          - backend:
              serviceName: rt-svc
              servicePort: 8080
            path: /


  tls:
    - hosts:
        - "isambard-support.gw4.ac.uk"
      secretName: isambard-support-tls
