apiVersion: apps/v1
kind: Deployment
metadata:
  name: rt-deploy
spec:
  selector:
    matchLabels:
      run: rt-pod
  template:
    metadata:
      name: rt-pod
      labels:
        run: rt-pod
    spec:
      containers:
      - name: postgres
        image: orchardup/postgresql
        env:
          - name: POSTGRESQL_USER
            value: rt_user
          - name: POSTGRESQL_PASS
            valueFrom:
              secretKeyRef:
                name: db-pass
                key: password
          - name: POSTGRESQL_DB
            value: rt4
          - name: SERVICE_ADDRESS
            value: isambard-support.gw4.ac.uk
        command: ["/usr/local/bin/run"]
        volumeMounts:
            - name: postgres-persistent-storage
              mountPath: /var/lib/postgresql/9.3
      - name: rt-run
        image: jrprice/rt-dev
        env:
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-pass
                key: password
          - name: O365_USER
            valueFrom:
              secretKeyRef:
                name: mail-user
                key: username
          - name: O365_PASS
            valueFrom:
              secretKeyRef:
                name: mail-pass
                key: password
          - name: SERVICE_ADDRESS
            value: isambard-support.gw4.ac.uk
        ports:
          - containerPort: 80
      volumes:
        - name: postgres-persistent-storage
          persistentVolumeClaim:
            claimName: postgresclaim
