apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresclaim
spec:
  storageClassName: store
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  hostPath:
    path: "/data"